# Generated by Django 3.0.7 on 2020-07-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_mybaseuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybaseuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mybaseuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
