# Generated by Django 3.0.7 on 2020-07-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_auto_20200729_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybaseuser',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
